apiVersion: v1
kind: Service
metadata:
  name: {{ include "rproxy.fullname" . }}
  labels:
{{ include "rproxy.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 2112
      targetPort: 2112
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "rproxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
